### PR TITLE
Add build&test process on push

### PR DESCRIPTION
**Pull request by raguiar9080**
To make sure things are working as expected, add the github workflow.
The original project uses circleCI, but for our case, github actions
works wonders as well and makes it unnecessary to have circleCI setup
for it.

Signed-off-by: Ruben Aguiar <r.aguiar9080@gmail.com>

### CODE REVIEW

**Comment by jstasiak** [comment]
We probably want this on pull requests as well?

**Comment by raguiar9080** [comment]
> We probably want this on pull requests as well?

I believe this works when any push happens, independent of the branch. So PR's are included.

**Comment by jstasiak** [comment]
There are no green checkmarks visible anywhere (not on commits, not in this PR) so I don't think it's working... See https://github.com/lune-climate/openapi-typescript-codegen/actions/runs/2097117343

**Comment by raguiar9080** [comment]
> There are no green checkmarks visible anywhere (not on commits, not in this PR) so I don't think it's working... See https://github.com/lune-climate/openapi-typescript-codegen/actions/runs/2097117343

Copy pasta issue. Was using CircleCI `command` instead of github workflow `run`. Fixed. Action is correctly passing 😄

**Review by jstasiak — APPROVED** [review]
Nice!

**Pull request merged**
