### PR TITLE
Convert all model properties to camelCase

### PR DESCRIPTION
**Pull request by raguiar9080**
They are currently all in snake_case (as usual for http endpoints) but
for the TS/JS ecosystem, we want them in the camelCase format.

Signed-off-by: Ruben Aguiar <r.aguiar9080@gmail.com>

### CODE REVIEW

**Comment by raguiar9080** [comment]
@jstasiak Changed to use the already existing camelCase functionality 👍

**Comment by jstasiak** [comment]
@raguiar9080 So this renames the properties in models but does it actually fills them with the data coming from the snake case properties that are result of JSON decoding and does it convert camel case properties to snake case when *sending* them over HTTP/JSON?

**Comment by raguiar9080** [comment]
> @raguiar9080 So this renames the properties in models but does it actually fills them with the data coming from the snake case properties that are result of JSON decoding and does it convert camel case properties to snake case when _sending_ them over HTTP/JSON?

Good catch. No it does not. For that, we will need to add interceptor to the axios client in a similar fashion as we do on the dashboard. Since https://github.com/lune-climate/openapi-typescript-codegen/pull/4 is not yet merged, I'll wait for that to be merged so changes can be made on this side in the generated luneClient 👍

**Comment by raguiar9080** [comment]
I've addded the interceptors to the `luneClient` template 👍

**Review by jstasiak — APPROVED** [review]

**Pull request merged**
