### PR TITLE
Improve handling of null-only enums

### PR DESCRIPTION
**Pull request by jstasiak**
We have this pattern in our public API OpenAPI specification[1] where we have this an enum like

    NullEnum:
      type: string
      x-lune-name: Null
      enum:
        - null nullable: true

which we use like so

  oneOf:
    - $ref: '#/components/schemas/DistanceCalculationMethod'
    - $ref: '#/components/schemas/NullEnum'

for reasons that aren't particularly important.

What's crucial is this code used to see this NullEnum and render its type as string which removed a lot of type safety from the generated code and from the code using it.

This is an attempt to fix that.

Note that:

* The generated type in this situation is "null | null" – the first null comes from the type of the enum itself, the second from the "nullable" property set to true. Probably not worth spending time trying to make this nicer, it's effectively just an enum anyway.
* The code can generate TS code with chunks of the schema copied there (no actual TS types generated, just schema pieces verbatim) which is what you see in the snapshot with "type: 'any'" in it.

  We don't use that feature so I left it alone.

  If we want for the copied piece of the schema to contain something other than "any" we can set model.type (below the line where we set model.base) to whatever we want.

The type is rendered through the base.hbs template called from typeGeneric.hbs.

[1] http://docs.lune.co/openapi.yml

Part-of: https://linear.app/lune/issue/LUN-2704/make-openapi-typescript-codegen-handle-null-values-better

### CODE REVIEW

**Comment by stoich** [comment]
I only have a loose understand of what it is that's going on here.

From what I can tell, we're overriding the "vanilla" openapi 3 to introduce our own custom plug-in that looks at enums that consist of `null` and nothing else and we make sure they are just null. Base on the PR description they were null | string before?

Does the "custom" openapi spec mean we can not upgrade our openapi version?

**Comment by stoich** [comment]
In the given example:
```
oneOf:
- $ref: '#/components/schemas/DistanceCalculationMethod'
- $ref: '#/components/schemas/NullEnum'
```
we've decided we do NOT want to have `DistanceCalculationMethod` be "nullable:true" ?

**Comment by jstasiak** [comment]
> From what I can tell, we're overriding the "vanilla" openapi 3 to introduce our own custom plug-in (...)


Not exactly. My understanding is this construct is a legal OpenAPI schema:

```
type: string
enum:
  - null
```

I may be wrong but I've seen no tool reject it yet. So I'd say the problem is the construct was always legal and the change is about making this tool (openapi-typescript-codegen) handle it better than before (before: `string`, after: `null`).


> In
> 
> ```
> NullEnum:
>   type: string
>   x-lune-name: Null
>   enum:
>     - null nullable: true
> ```
> 
> why exactly do we add "nullable: true" ?

because last time I checked both of these were needed to make the runtime request/response validator used in Lune backend to permit `null` values. For the purposes of *this* project it doesn't really matter why we do it though.

**Comment by jstasiak** [comment]
> In the given example:
> 
> ```
> oneOf:
> - $ref: '#/components/schemas/DistanceCalculationMethod'
> - $ref: '#/components/schemas/NullEnum'
> ```
> 
> we've decided we do NOT want to have `DistanceCalculationMethod` be "nullable:true" ?

That'd

* Be redundant (as `NullEnum` already has that)
* Not work reliably (because per the message above merely adding `nullable: true` won't work with our runtime validation and any nullable enums also need an explicit `null` member)

**Review by stoich — APPROVED** [review]

**Comment by stoich** [comment]
> > In the given example:
> > ```
> > oneOf:
> > - $ref: '#/components/schemas/DistanceCalculationMethod'
> > - $ref: '#/components/schemas/NullEnum'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > we've decided we do NOT want to have `DistanceCalculationMethod` be "nullable:true" ?
> 
> That'd
> 
> * Be redundant (as `NullEnum` already has that)
> * Not work reliably (because per the message above merely adding `nullable: true` won't work with our runtime validation and any nullable enums also need an explicit `null` member)

Right... but we could NOT have 
- $ref: '#/components/schemas/NullEnum'
and we could add null and nullable:true to `DistanceCalculationMethod` and it would be support null as desired? (I can see why we wouldn't want to do it tho )

**Comment by jstasiak** [comment]
Yes

**Review by raguiar9080 — APPROVED** [review]
Very nice PR description

**Pull request merged**
